services: 
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: